# Generated by Django 4.1.7 on 2023-11-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='damage_name',
            field=models.CharField(choices=[('', '選択肢から選んでください'), ('0', '腐食'), ('1', '亀裂'), ('2', 'ゆるみ・脱落'), ('3', '破断'), ('4', '防食機能の劣化'), ('5', 'ひびわれ'), ('6', '剥離・鉄筋露出'), ('7', '漏水・遊離石灰'), ('8', '抜け落ち'), ('9', '補修・補強材の損傷'), ('10', '床版ひびわれ'), ('11', 'うき'), ('12', '遊間の異常'), ('13', '路面の凹凸'), ('14', '舗装の異常'), ('15', '支承部の機能障害'), ('16', 'その他'), ('17', '定着部の異常'), ('18', '変色・劣化'), ('19', '漏水・滞水'), ('20', '異常な音・振動'), ('21', '異常なたわみ'), ('22', '変形・欠損'), ('23', '土砂詰まり'), ('24', '沈下・移動・傾斜'), ('25', '洗堀')], default='', max_length=20),
        ),
    ]
