# Generated by Django 4.1.7 on 2023-11-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_product_price_product_damage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='findings',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='picture_comment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
