# Generated by Django 4.1.7 on 2023-11-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_product_findings_product_picture_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_comment',
        ),
    ]
