# Generated by Django 4.2.7 on 2023-11-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_product_img_alter_product_damage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
